cron: false
data_dir: "data"
db_dir: "storage"
stocks_file: "./storage/stocks.csv"
selected_file: "./storage/selected.csv"
alarm_a: 7
alarm_b: 8
alarm_c: 9
max_total: 6000000000
min_total: 200000000000
max_price_day: 5


push:
  enable: true
  type: "groupchat"
  url: "https://message.1more.cn:5443/api/send_message"
  admin: "admin@message.1more.cn"
  admin_pass: "abcd_123"
  user: "ehelo@conference.message.1more.cn"
