cron: false
data_dir: "data"
db_dir: "storage"
stocks_file: "./storage/stocks.csv"
selected_file: "./storage/selected.csv"
alarm_at: 7
max_total: 6000000000
min_total: 200000000000
max_price_day: 5


push:
  enable: false
  url: "https://message.1more.cn:5378/api/send_message"
  admin: "admin@message.1more.cn"
  admin_pass: "abcd_123"
  user: "stock@message.1more.cn"
